In [1]:
from tensorflow.keras.datasets import mnist

from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Input
import numpy as np
import matplotlib.pyplot as plt

In [2]:
input_shape = (28, 28, 1)

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(X_train.shape)
print(Y_train.shape)

(60000, 28, 28)
(60000,)


In [3]:
# Make sure images have shape (28, 28, 1)
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

Y_train = to_categorical(Y_train, num_classes = 10)
Y_test = to_categorical (Y_test, num_classes = 10)

print(X_train.shape)
print(Y_train.shape)

print(X_train[1].T)
print(Y_train[1])

(60000, 28, 28, 1)
(60000, 10)
[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  76  85
    85  85  86  85  85  28   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   7  57 198 246 252
   252 252 253 252 252 199  25   0   0   0   0]
  [  0   0   0   

In [4]:
print("X_train[1].mean()", X_train[1].mean())
print("X_train[1].std()", X_train[1].std())

X_train[1].mean() 39.661989795918366
X_train[1].std() 83.88715868331147


In [5]:
for i in range(X_train.shape[0]):
    X_train[i] = (X_train[i]-X_train[i].mean())/X_train[i].std()
    
for i in range(X_test.shape[0]):
    X_test[i] = (X_test[i]-X_test[i].mean())/X_test[i].std()  

In [6]:
print(Y_train[1])
print(X_train[1].T)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 2 2 2 2 2 1 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 2 2 2 1 2 2 2 2 1 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 1 2 2 1 0 0 0 0 0 1 2 2 2 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0]
  [0 0 0 0 0 0 0 0 1 2 2 2 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0]
  [0 0 0 0 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 2 2 1 0 0 0 0]
  [0 0 0 0 0 0 0 2 2 2 1 0 0 0 0 0 0 0 0 0 1 2 2 0 0 0 0 0]
  [0 0 0 0 0 0 2 2 2 1 0 0 0 0 0 0 0 0 0 0 2 2 1 0 0 0 0 0]
  [0 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0]
  [0 0 0

In [12]:
X_train.dtype

dtype('uint8')